config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'vlogs#index'
  resources :vlogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vlog.rb
class Vlog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vlogs_controller.rb
class VlogsController < ApplicationController
  before_action :set_vlog, only: [:show, :edit, :update, :destroy]

  # GET /vlogs
  # GET /vlogs.json
  def index
    @vlogs = Vlog.all
  end

  # GET /vlogs/1
  # GET /vlogs/1.json
  def show
  end

  # GET /vlogs/new
  def new
    @vlog = Vlog.new
  end

  # GET /vlogs/1/edit
  def edit
  end

  # POST /vlogs
  # POST /vlogs.json
  def create
    @vlog = Vlog.new(vlog_params)

    respond_to do |format|
      if @vlog.save
        format.html { redirect_to @vlog, notice: 'Vlog was successfully created.' }
        format.json { render :show, status: :created, location: @vlog }
      else
        format.html { render :new }
        format.json { render json: @vlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vlogs/1
  # PATCH/PUT /vlogs/1.json
  def update
    respond_to do |format|
      if @vlog.update(vlog_params)
        format.html { redirect_to @vlog, notice: 'Vlog was successfully updated.' }
        format.json { render :show, status: :ok, location: @vlog }
      else
        format.html { render :edit }
        format.json { render json: @vlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vlogs/1
  # DELETE /vlogs/1.json
  def destroy
    @vlog.destroy
    respond_to do |format|
      format.html { redirect_to vlogs_url, notice: 'Vlog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vlog
      @vlog = Vlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vlog_params
      params.fetch(:vlog, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vlogs_helper.rb
module VlogsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Demo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/vlogs/_form.html.slim
= form_with(model: vlog, local: true) do |form|
  - if vlog.errors.any?
    #error_explanation
      h2
        = pluralize(vlog.errors.count, "error")
        | prohibited this vlog from being saved:
      ul
        - vlog.errors.full_messages.each do |message|
          li= message
  .actions
    = form.submit

app/views/vlogs/edit.html.slim
h1 Editing Vlog
= render 'form', vlog: @vlog
= link_to 'Show', @vlog
| \
= link_to 'Back', vlogs_path

app/views/vlogs/index.html.slim
p#notice= notice
h1 Vlogs
table
  thead
    tr
      th colspan="3"
  tbody
    - @vlogs.each do |vlog|
      tr
        td= link_to 'Show', vlog
        td= link_to 'Edit', edit_vlog_path(vlog)
        td= link_to 'Destroy', vlog, method: :delete, data: { confirm: 'Are you sure?' }
br/
= link_to 'New Vlog', new_vlog_path

app/views/vlogs/new.html.slim
h1 New Vlog
= render 'form', vlog: @vlog
= link_to 'Back', vlogs_path

app/views/vlogs/show.html.slim
p#notice= notice
= link_to 'Edit', edit_vlog_path(@vlog)
| \
= link_to 'Back', vlogs_path